### ISSUE TITLE
Web page development

### ISSUE THREAD

**Issue by Antosebastian** [toshinuraj/capstone-project-2020#10]

**Comment by mikeshams** [comment]
1. what issues did you or others might face with developing a webpage for the BBB?
2. How to resolve them?

**Comment by toshinuraj** [comment]
1a.it took a while to understand about HTML like syntax were very new for me.
  b.i didn't check the file extension column for the first time, so I was not able to get the HTML file 
  c.  tough to spot an error if  we make any, we could get the error only from the webpage
2.i went through some basic courses about HTML in Linkedin learning,udemy
3.some youtube tutorials were  also helped in creating this webpage
