### ISSUE TITLE
Pump system

### ISSUE THREAD

**Issue by Antosebastian** [toshinuraj/capstone-project-2020#17]

**Comment by mikeshams** [comment]
1. what issues did you or others might face when connecting a relay to the beagle-bone in terms of hardware and software?
2. How did you solve them?

**Comment by Antosebastian** [comment]
1. It was presumed that a single supply was required for relay and pump; but that poses to be separate.
    Normally open and normally closed connection of the relay might seem a bit confusing.
    Enabling the related gpio connection requires the use of file pointer in C program.

2. Solutions:
    1. the relay may be power by BBB directly, while the pump should be powered externally though for short term or demonstration purpose it may be connected to sys_5v pin(P9 pin 7)(only if the system connected consumes 4.5 v or less).
    2. there is NC(normally closed) and NO(normally open) pins on the relay; NO allows current when the relay is energized and NC allows current when the relay is not energized. 
    3. file handling is available in C; fopen() to open an external file and fclose() to close an external file. File handling in C makes use of file pointers. synopsis for defining a file pointer is FILE *<pointer_name> 
        It is also worth noting the pinout of Beaglebone black as to which GPIO pin should be enabled.
