### ISSUE TITLE
Design hardware schematics

### ISSUE THREAD

**Issue by mikeshams** [toshinuraj/capstone-project-2020#18]

**Comment by mikeshams** [comment]
Please add more slides to explain how to do schematics design!

**Comment by mikeshams** [comment]
1. How do you share your screen on Adobe Connect if you are going to use Linux?

**Comment by toshinuraj** [comment]
1.install team viewer software in both laptops(one with windows and one with Linux os)
2.open team viewer application in both laptops
3 first.login TeamViewer application in one laptop which has windows os 
4..copy and paste the id and password of the Linux user(now bridging enabled between windows os and Linux os)
5. A TeamViewer ID is unique, will always stay the same for every device and can be used to contact that device from any other instance of TeamViewer. Passwords are generated randomly with every start of TeamViewer.
6. open adobe connect of the Linux user  and click on the share screen icon
