### ISSUE TITLE
MCU setup

### ISSUE THREAD

**Issue by Antosebastian** [toshinuraj/capstone-project-2020#3]
BBB wireless initial setup
Debian image

**Comment by mikeshams** [comment]
1. What's your comment regarding BBB Debian image flashing?

**Comment by Antosebastian** [comment]
Beaglebone Black Wireless came in with the latest image. Hence there was no need to flash an image.
However to flash an image usingbelana etcher sd card, 
#go to https://beagleboard.org/latest-images;download the image
#Use belenaetcher to to write the image to the memory card
#insert the memory card on power down; press down s2 button and give connection to bbb using usb
#now the bbb starts to run from the image on the memory card.
#flash the image from memory card to eMMC
        ->uncomment line startiing with cmdline=..... in the file uEnv.txt
#shutdown, remove the sd card and reboot again to run from the latest image on the eMMMC
