### ISSUE TITLE
Power management

### ISSUE THREAD

**Issue by Antosebastian** [toshinuraj/capstone-project-2020#5]
BBB hibernation
sleep()

**Comment by mikeshams** [comment]
Explain how to shoot the trouble!

**Comment by mikeshams** [comment]
1. what issues did you or others might face with power management for a BBB?

**Comment by Antosebastian** [comment]
Though AM335x processor has different power management feature, most of theses cant be accessed from beaglebone black due to the limitations in the bbb hardware.
the first and foremost being the absence of a battery backed real time clock on the beaglebone black.
Hence power management by deep sleep is not directly possible.
However on the latest images sleeping to a standby mode is possible.
