### ISSUE TITLE
Open weather map API interfacing

### ISSUE THREAD

**Issue by Antosebastian** [toshinuraj/capstone-project-2020#6]

**Comment by mikeshams** [comment]
1. What is the meaning of API?
2. How to carry the OpenWeatherMap API codes into embedded C?
3. why do we need Nano?
4. what issues did you or others might face working with this service?

**Comment by mikeshams** [comment]
5. Explain why do you need this service in one paragraph?

**Comment by jerin1712** [comment]
Ans1. Application Programming Interface

Ans2. There are no explicit libraries defined in C to access xml and json file. Hence we have used embedded python in C to parse the xml/json file into a text file saved locally on the disk, which will be used to manipulate the code.

Ans3.  nano is an easy to use command line text editor for linux operating systems. includes all the basic functionality you'd expect from a regular text editor, like syntax highlighting

Ans4.  1.it is not safe and easy hack-able. the data can be easily tracked and hacked. 
2.Testing teams may find validating the parameters sent through API requests is challenge. 
3.API calls need to appear in a specific order to work correctly, This creates a sequencing challenge.

Ans5. An API is a  definitions and conventions for building and integrating application software.  API stands for application programming interface.APIs let your item or administration communicate with different product and services without realizing how they're actualized. This can improve and simplify application advancement, setting aside time and money. At the point when you're planning new instruments and items, APIs give you adaptability; improve plan, . flexibility ,organization, and use; and give chances to innovation.APIs are in some cases thought of as agreements, with documentation that speaks to an understanding between parties: If party 1 sends remote request structured a particular way,, this is the way party 2's product will react.
