### ISSUE TITLE
Sensor interfacing 2 - Temperature and Humidity

### ISSUE THREAD

**Issue by Antosebastian** [toshinuraj/capstone-project-2020#8]

**Comment by mikeshams** [comment]
1. what issues did you or others might face with connecting the humidity/ temperature sensor to the BBB Wireless in terms of hardware and software?
2. how did you resolve them?

**Comment by Antosebastian** [comment]
1. a)The DHT sensor libraries provided by Adafruit is in Python
    b)Data is transferred from a single pin; learning the way data transfer occurs on DHT
    c)Adafruit DHT library support for Python 2.7 has stopped and /or face difficulty
    d)Python 3 does not support any functions in python 2.7
2. a) Python is being  run through extending python in c(Embedding Python in Another Application)
    b) https://www.youtube.com/watch?v=reYa_4rh0-w&feature=youtu.be
    c) Python3 is recommended.

the following links helped a lot among many others
https://github.com/adafruit/Adafruit_Python_DHT
https://docs.python.org/3/extending/embedding.html?highlight=pfunc#very-high-level-embedding
https://stackoverflow.com/questions/25316485/call-a-python-function-from-within-a-c-program
