### ISSUE TITLE
Cloud connection

### ISSUE THREAD

**Issue by Antosebastian** [toshinuraj/capstone-project-2020#9]

**Comment by mikeshams** [comment]
1. what issues did you or others might face when connecting the BBB to ThingSpeak?
2. How to resolve them?

**Comment by jerin1712** [comment]
the first issue that i faced is the connection problem with the BBB. My BBB gets disconnected sometimes when going for real time data upload. tho resolve this i had to shutdown the BBB and then connect it back again. and this time i had to start a new terminal to write down the commands. 

secondly the delay of 15 sec is prominent with the free version. But that didn't affected us much as our values were uploaded in every 1 hour.

**Comment by mikeshams** [comment]
Demonstrate the task in real time.
